# WQD7005 - Data Mining
## FINAL EXAM

### Matrix Number : 17043640

### Name                 : Gunasegarran Magadevan

<center><img src='questions/q1.png'></center>

In [1]:
from bs4 import BeautifulSoup
import urllib.request
import pandas as pd
import numpy as np
import csv
from pathlib import Path

In [2]:
csvExist = Path('goldRate.csv') #creating a file in csv extention
#Only enable when overwriting with new columns
#if csvExist.is_file():
#    pass
#else:
with open ('goldRate.csv','wb') as createFile: #This line will create a csv file under name webcrawler
        filewriter = csv.writer(createFile)

url = "https://www.investing.com/commodities/gold-historical-data"
req = urllib.request.Request(url, data=None, headers={'User-Agent': 'Chrome/35.0.1916.47'})

soup = BeautifulSoup(urllib.request.urlopen(req).read(),"lxml")

#extract data 
rows = soup.find('table',{'class': 'genTbl closedTbl historicalTbl'}).findAll('tr')[1:]
data = []
for row in rows:
    cols = row.find_all('td')
    cols = [ele.text.strip(' ') for ele in cols]
    data.append([ele for ele in cols if ele])
 
#extract column names 
colnames = soup.find('table',{'class': 'genTbl closedTbl historicalTbl'}).findAll('tr')[:1]
col_names = []
for col in colnames:
    cols = col.find_all('th')
    cols = [ele.text.strip() for ele in cols]
    col_names.append(cols)
col_names = col_names[0]
    
#Write data to files
df1 = pd.DataFrame(data,columns = col_names)
df1['Change %'] = list(map(lambda x: x[:-1], df1['Change %'].values))
df1['Vol.'] = list(map(lambda x: x[:-1], df1['Vol.'].values))
df1=df1.rename(columns={"Date":"Date","Price":"PriceUSD", "Open":"OpenUSD", 
                                                    "High":"HighUSD","Low":"LowUSD", 
                                                    "Vol.":"VolumeUSD", "Change %":"Change"})
df1.to_csv('goldRate.csv',mode = 'w', index=False)
df1.head()

           Date Price(USD) Open(USD) High(USD)  Low(USD) Volume(USD) Change
0  Jun 12, 2020   1,737.30  1,733.60  1,753.00  1,728.20              -0.14
1  Jun 11, 2020   1,739.80  1,746.60  1,754.90  1,727.50      205.35   1.11
2  Jun 10, 2020   1,720.70  1,718.90  1,749.40  1,714.10      198.76  -0.07
3  Jun 09, 2020   1,721.90  1,703.90  1,729.40  1,697.60      182.91   0.99
4  Jun 08, 2020   1,705.10  1,686.70  1,707.60  1,680.70      154.77   1.31

In [3]:
csvExist = Path('currencyExchange.csv') #creating a file in csv extention
#Only enable when overwriting with new columns
#if csvExist.is_file():
#    pass
#else:
with open ('currencyExchange.csv','wb') as createFile: #This line will create a csv file under name webcrawler
        filewriter = csv.writer(createFile)

url = "https://www.investing.com/currencies/usd-myr-historical-data"
req = urllib.request.Request(url, data=None, headers={'User-Agent': 'Chrome/35.0.1916.47'})

soup = BeautifulSoup(urllib.request.urlopen(req).read(),"lxml")

#extract data 
rows = soup.find('table',{'class': 'genTbl closedTbl historicalTbl'}).findAll('tr')[1:]
data = []
for row in rows:
    cols = row.find_all('td')
    cols = [ele.text.strip(' ') for ele in cols]
    data.append([ele for ele in cols if ele])
 
#extract column names 
colnames = soup.find('table',{'class': 'genTbl closedTbl historicalTbl'}).findAll('tr')[:1]
col_names = []
for col in colnames:
    cols = col.find_all('th')
    cols = [ele.text.strip() for ele in cols]
    col_names.append(cols)
col_names = col_names[0]
    
#Write data to files
df2 = pd.DataFrame(data,columns = col_names)
df2['Change %'] = list(map(lambda x: x[:-1], df2['Change %'].values))
df2=df2.rename(columns={"Date":"Date","Price":"PriceUSD", "Open":"OpenUSD", 
                                                    "High":"HighUSD","Low":"LowUSD", 
                                                    "Change %":"Change"})
df2.to_csv('currencyExchangeMYR2USD.csv',mode = 'w', index=False)
df2.head()

           Date Price(USD) Open(USD) High(USD) Low(USD) Change
0  Jun 12, 2020     4.2705    4.2575    4.2880   4.2550   0.49
1  Jun 11, 2020     4.2495    4.2515    4.2600   4.2365  -0.05
2  Jun 10, 2020     4.2515    4.2750    4.2805   4.2505  -0.56
3  Jun 09, 2020     4.2755    4.2610    4.2785   4.2450   0.36
4  Jun 08, 2020     4.2600    4.2610    4.2610   4.2600  -0.18

In [4]:
csvExist = Path('borneoOilUSD.csv') #creating a file in csv extention
#Only enable when overwriting with new columns
#if csvExist.is_file():
#    pass
#else:
with open ('borneoOilUSD.csv','wb') as createFile: #This line will create a csv file under name webcrawler
        filewriter = csv.writer(createFile)

url = "https://www.investing.com/equities/borneo-oil-bhd-historical-data"
req = urllib.request.Request(url, data=None, headers={'User-Agent': 'Chrome/35.0.1916.47'})

soup = BeautifulSoup(urllib.request.urlopen(req).read(),"lxml")

#extract data 
rows = soup.find('table',{'class': 'genTbl closedTbl historicalTbl'}).findAll('tr')[1:]
data = []
for row in rows:
    cols = row.find_all('td')
    cols = [ele.text.strip(' ') for ele in cols]
    data.append([ele for ele in cols if ele])
 
#extract column names 
colnames = soup.find('table',{'class': 'genTbl closedTbl historicalTbl'}).findAll('tr')[:1]
col_names = []
for col in colnames:
    cols = col.find_all('th')
    cols = [ele.text.strip() for ele in cols]
    col_names.append(cols)
col_names = col_names[0]
    
#Write data to files
df3 = pd.DataFrame(data,columns = col_names)
df3['Change %'] = list(map(lambda x: x[:-1], df3['Change %'].values))
df3['Vol.'] = list(map(lambda x: x[:-1], df3['Vol.'].values))
df3=df3.rename(columns={"Date":"Date","Price":"PriceUSD", "Open":"OpenUSD", 
                                                    "High":"HighUSD","Low":"LowUSD", 
                                                    "Vol.":"VolumeUSD", "Change %":"Change"})
df3.to_csv('borneoOilUSD.csv',mode = 'w', index=False)
df3.head()

           Date Price(USD) Open(USD) High(USD) Low(USD) Volume(USD)  Change
0  Jun 12, 2020      0.035     0.030     0.035    0.025       18.84   16.67
1  Jun 11, 2020      0.030     0.030     0.035    0.030       77.77    0.00
2  Jun 10, 2020      0.030     0.030     0.035    0.030        3.20    0.00
3  Jun 09, 2020      0.030     0.035     0.035    0.030        4.55    0.00
4  Jun 05, 2020      0.030     0.030     0.035    0.030        8.68  -14.29

<center><img src='questions/q2.png'></center>

In [5]:
# list column name of df 
print(list(df1.columns))
print(list(df2.columns))
print(list(df3.columns))

['Date', 'Price(USD)', 'Open(USD)', 'High(USD)', 'Low(USD)', 'Volume(USD)', 'Change']
['Date', 'Price(USD)', 'Open(USD)', 'High(USD)', 'Low(USD)', 'Change']
['Date', 'Price(USD)', 'Open(USD)', 'High(USD)', 'Low(USD)', 'Volume(USD)', 'Change']

In [6]:
# dtype of each columns in df
print(list(df1.dtypes))
print(list(df2.dtypes))
print(list(df3.dtypes))

[dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O')]
[dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O')]
[dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O')]

In [7]:
# importing module 
import sqlite3 
import csv
  
# connecting to the database  
connection = sqlite3.connect("wqd7005_final.db") 
  
# cursor  
crsr = connection.cursor() 

# SQL command to drop a table in the database if exist
crsr.execute("DROP TABLE IF EXISTS goldRate;")
crsr.execute("DROP TABLE IF EXISTS currencyExchangeMYR2USD;")
crsr.execute("DROP TABLE IF EXISTS borneoOilUSD;")


# SQL command to create a table in the database 
createTableA = """CREATE TABLE goldRate (  
Date DATETIME,
PriceUSD FLOAT,
OpenUSD FLOAT,
HighUSD FLOAT,
LowUSD FLOAT,
VolumeUSD FLOAT,
Change FLOAT);"""

createTableB = """CREATE TABLE currencyExchangeMYR2USD (  
Date DATETIME,
PriceUSD FLOAT,
OpenUSD INTEGER,
HighUSD FLOAT,
LowUSD INTEGER,
Change FLOAT);"""

createTableC = """CREATE TABLE borneoOilUSD (  
Date DATETIME,
PriceUSD FLOAT,
OpenUSD FLOAT,
HighUSD FLOAT,
LowUSD FLOAT,
VolumeUSD FLOAT,
Change FLOAT);"""
  
# execute the statement createTable
crsr.execute(createTableA)
crsr.execute(createTableB)
crsr.execute(createTableC)

# SQL command to list down the table details 
crsr.execute("PRAGMA table_info(goldRate);")
crsr.execute("PRAGMA table_info(currencyExchangeMYR2USD);")
crsr.execute("PRAGMA table_info(borneoOilUSD);")

read_data = pd.read_csv((r'goldRate.csv'), sep=",",index_col=[0])
read_data = pd.read_csv((r'currencyExchangeMYR2USD.csv'), sep=",",index_col=[0])
read_data = pd.read_csv((r'borneoOilUSD.csv'), sep=",",index_col=[0])
 # Insert the values from the csv file into the table
read_data.to_sql('goldRate', connection, if_exists='append', index = False)
read_data.to_sql('currencyExchangeMYR2USD', connection, if_exists='append', index = False)
read_data.to_sql('borneoOilUSD', connection, if_exists='append', index = False)

# execute the command to fetch all the data from the table emp 
crsr.execute("SELECT * FROM goldRate LIMIT 3;")  

# store all the fetched data in the ans variable 
ans = crsr.fetchall() 

print("SELECT * FROM goldRate LIMIT 5;  \n",ans)


# To save the changes in the files. Never skip this.  
# If we skip this, nothing will be saved in the database. 
connection.commit() 
  
# close the connection 
connection.close()

OperationalError: near "(": syntax error